/*
 * This file was generated by the Gradle 'init' task.
 */
rootProject.name = "MapManager"
include(":MapManager-API", ":MapManager-Core")

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven(url = "https://repo.papermc.io/repository/maven-public/")
        maven(url = "https://repo.onarandombox.com/content/groups/public/")
        maven(url = "https://oss.sonatype.org/content/groups/public/")
        maven(url = "https://repo.phoenix616.dev/")
        maven(url = "https://jitpack.io")
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.startsWith("org.jetbrains.kotlin")) {
                useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.0")
            }
        }
    }
}
