/*
 * This file was generated by the Gradle 'init' task.
 */
description = "v1_16_R1"

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm") version "2.3.0"

}

dependencies {
    implementation(kotlin("stdlib"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    compileOnly("org.mvplugins.multiverse.core:multiverse-core:5.7.2")
    compileOnly("net.luckperms:api:5.3")
    compileOnly("com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT")
    implementation(project(":MapManager-API"))
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_25)
    }
}
